# @package _global_
to_tensor:
  _target_: emg2qwerty.transforms.ToTensor
  fields: [emg_left, emg_right]

band_rotation:
  _target_: emg2qwerty.transforms.ForEach  # i.i.d rotation offset for each band
  transform:
    _target_: emg2qwerty.transforms.RandomBandRotation
    offsets: [-1, 0, 1]

temporal_jitter:
  _target_: emg2qwerty.transforms.TemporalAlignmentJitter
  max_offset: 120  # Max 60ms jitter for 2kHz EMG

logspec:
  _target_: emg2qwerty.transforms.LogSpectrogram
  n_fft: 64
  hop_length: 16  # Downsamples from 2kHz to 125Hz

specaug:
  _target_: emg2qwerty.transforms.SpecAugment
  n_time_masks: 3
  time_mask_param: 25  # Max 200ms per time mask for 125Hz spectrogram
  n_freq_masks: 2
  freq_mask_param: 4

intaug:
  _target_: emg2qwerty.transforms.IntensityAugment
  intensity_mod: 0.2
  pr: 0.3

usererroraug:
  _target_: emg2qwerty.transforms.UserErrorAugment
  pr: 0.1

gaussiannoise:
  _target_: emg2qwerty.transforms.GaussianNoise
  noise: 0.1
  pr: 0.4

channelmute:
  _target_: emg2qwerty.transforms.RemoveChannelAugment
  channels: [0]

transforms:
  train:
    - ${to_tensor}
    - ${band_rotation}
    - ${temporal_jitter}
    - ${gaussiannoise}
    - ${logspec}
    - ${specaug}
    - ${intaug}
    - ${usererroraug}

  val:
    - ${to_tensor}
    - ${logspec}
    - ${channelmute}

  test: ${transforms.val}
